# Generated by Django 3.1.7 on 2023-02-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitrix_1c',
            name='tip_podkl',
        ),
        migrations.RemoveField(
            model_name='bitrix_1c',
            name='title',
        ),
        migrations.AddField(
            model_name='bitrix_1c',
            name='planado_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bitrix_1c',
            name='date_tg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bitrix_1c',
            name='status',
            field=models.TextField(default=0, max_length=200, null=True),
        ),
    ]
