# Generated by Django 3.1.7 on 2023-03-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0002_auto_20230228_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix_1c',
            name='check_one_time_servise',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
