# Generated by Django 3.1.7 on 2023-03-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0003_bitrix_1c_check_one_time_servise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montajnik_1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_mont', models.CharField(max_length=200, null=True)),
                ('id_mont', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
