# Generated by Django 3.1.7 on 2023-03-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0005_auto_20230303_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='montajnik_1c',
            options={'verbose_name': 'Монтажники', 'verbose_name_plural': 'Монтажники'},
        ),
    ]
