# Generated by Django 3.1.7 on 2023-03-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0007_montajnik_1c_bx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montajnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_mont', models.CharField(max_length=200, null=True)),
                ('id_mont', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Montajnik_1C',
        ),
    ]
