# Generated by Django 3.1.7 on 2023-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0008_auto_20230309_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montajnik_1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx_id', models.CharField(max_length=20, null=True)),
                ('fio_mont', models.TextField(max_length=200, null=True)),
                ('id_mont', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Монтажники',
                'verbose_name_plural': 'Монтажники',
            },
        ),
        migrations.DeleteModel(
            name='Montajnik',
        ),
    ]
