# Generated by Django 3.1.7 on 2023-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_report_1c', '0009_auto_20230309_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix_1c',
            name='type_ovk',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
